### ISSUE TITLE
PR #221 Causes Errors with Celery

### ISSUE THREAD

**Issue by TariqAHassan** [ClearcodeHQ/pytest-redis#222]
### What action do you want to perform

Revert PR https://github.com/ClearcodeHQ/pytest-redis/pull/221 or correct the bug it creates.

### What are the results

PR https://github.com/ClearcodeHQ/pytest-redis/pull/221 creates the following bug, at least when used with `celery`:

```
Traceback (most recent call last):
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/.../lib/python3.7/site-packages/celery-4.4.0-py3.7.egg/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/.../lib/python3.7/site-packages/kombu-4.6.7-py3.7.egg/kombu/asynchronous/hub.py", line 297, in create_loop
    tick_callback()
  File "/.../lib/python3.7/site-packages/kombu-4.6.7-py3.7.egg/kombu/transport/redis.py", line 1063, in on_poll_start
    cycle_poll_start()
  File "/.../lib/python3.7/site-packages/kombu-4.6.7-py3.7.egg/kombu/transport/redis.py", line 329, in on_poll_start
    self._register_BRPOP(channel)
  File "/.../lib/python3.7/site-packages/kombu-4.6.7-py3.7.egg/kombu/transport/redis.py", line 311, in _register_BRPOP
    if not self._client_registered(channel, channel.client, 'BRPOP'):
  File "/.../lib/python3.7/site-packages/kombu-4.6.7-py3.7.egg/kombu/transport/redis.py", line 306, in _client_registered
    (channel, client, cmd) in self._chan_to_sock)
```

### What are the expected results

No Error.

**Comment by fizyk** [comment]
@TariqAHassan please pin the `redis` version in your project. The PR you're referring is just changing requirements for the dev/test env of pytest-redis. 
Plus I don't see anything related to pytest-redis itself in your traceback.

If you'll look closely pytest-redis's setup file, it ought to work with redis package from 3 and up. 

I think, that the issue you're referring is either with `redis` package itself, or `kombu/celery`
